#spring:
#  config:
#    import: configserver:http://localhost:8085
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#        
#  endpoint:
#    health:
#      show-details: always
#
#
#		
# 

spring:
  config:
    import: "configserver:http://localhost:8085"

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always		
 